services:
  zerotier:
    image: docker.io/zyclonite/zerotier:1.12.2
    volumes:
      - ./zt:/var/lib/zerotier-one
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=0.0.0.0/0
    ports:
      - 9993:9993
  zerotier-edge:
    build: .
    command: -H 0.0.0.0 -Z http://zerotier:9993
    volumes:
      - ./zt:/var/lib/zerotier-one
    ports:
      - 9394:9394
